# This script is used to compare a Dymo-generated PDF against one generated by the Renderer.
#
# Setup:
#
#     gem install combine_pdf
#
# Usage:
#
#     ruby overlay_test.rb sample_nametag.label sample_nametag.pdf out.pdf sample_nametag_overlay.pdf
#
# The final filename will be both the reference PDF and the generated PDF combined,
# one on top of the other, for comparison.

require 'combine_pdf'
require_relative './renderer'

(label_filename, pdf_filename, out_filename, overlay_filename) = ARGV

out = Renderer.new(xml: File.read(label_filename), params: {}).render
File.write(out_filename, out)

actual = CombinePDF.load(out_filename).pages[0]
pdf = CombinePDF.load(pdf_filename)
pdf.pages.each { |page| page << actual }
pdf.save overlay_filename
